server:
  port: 8081

spring:
  application:
    name: springboot-login-redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_login?&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    userName: root
    password: root
  redis:
    host: 114.213.212.69
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100

mybatis:
  configuration:
    map-underscore-to-camel-case: true
