server:
  port: 8081

spring:
  application:
    name: springboot-login-wechat
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/db_login?&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    userName: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

