server.port=8080

#spring.task.execution.pool.core-size=
#spring.task.execution.pool.max-size=
#spring.task.execution.pool.queue-capacity=
#spring.task.execution.pool.keep-alive=
#spring.task.execution.thread-name-prefix=

#spring.task.scheduling.pool.size=
#spring.task.scheduling.thread-name-prefix=